import{a as b,S as L,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const w="51594808-2f8a269bf80026fef40a32938",S="https://pixabay.com/api/";async function v(o){return(await b.get(S,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),q=new L(".gallery a");function P(o){const r=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:s,comments:y,downloads:g})=>`
    <li class="photo-card">
      <a href="${i}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${y}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function B(){m.innerHTML=""}function E(){h.classList.remove("hidden")}function R(){h.classList.add("hidden")}function $(){document.querySelector(".load-more-btn").classList.remove("hidden")}function l(){document.querySelector(".load-more-btn").classList.add("hidden")}const c=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let d="",u=1,f=0;c.addEventListener("submit",async o=>{if(o.preventDefault(),d=c.searchText.value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}u=1,B(),l(),await p(),c.reset()});M.addEventListener("click",async()=>{u+=1,await p(!0)});async function p(o=!1){E();try{const r=await v(d),{hits:n,totalHits:i}=r;if(f=i,n.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}P(n),u*15<f?$():(l(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),o&&O()}catch{a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{R()}}function O(){const o=document.querySelector(".gallery .photo-card");if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:2*r,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
