import{a as b,S as w,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const v="https://pixabay.com/api/",S="51594808-2f8a269bf80026fef40a32938";async function E(o,r=1){const t={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await b.get(v,{params:t})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".loader-text"),y=document.querySelector(".load-more-btn");let q=new w(".gallery a");function R(o){const r=o.map(t=>`
      <li class="photo-card">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function B(){p.innerHTML=""}function $(){h.classList.remove("hidden"),m.classList.remove("hidden")}function x(){h.classList.add("hidden"),m.classList.add("hidden")}function M(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}function P(){const o=document.querySelector(".gallery .photo-card");if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const l=document.querySelector(".form"),g=document.querySelector(".load-more-btn");let u="",i=1,f=0;l.addEventListener("submit",async o=>{if(o.preventDefault(),u=l.elements["search-text"].value.trim(),!u){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}i=1,B(),d(),await L(),l.reset()});g.addEventListener("click",async()=>{i+=1,await L(!0)});async function L(o=!1){$();try{const r=await E(u,i),{hits:t,totalHits:s}=r;if(f=s,t.length===0){a.info({title:"No results",message:"No images found. Try again!",position:"topRight"}),d();return}R(t),i*15<f?M():(d(),a.info({title:"End",message:"You have reached the end of search results.",position:"topRight"})),o&&P()}catch{a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{x()}}g.classList.add("hidden");
//# sourceMappingURL=index.js.map
