import{a as L,S as w,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const S="51594808-2f8a269bf80026fef40a32938",v="https://pixabay.com/api/";async function q(o){return(await L.get(v,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),P=new w(".gallery a");function B(o){const r=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:s,comments:g,downloads:b})=>`
    <li class="photo-card">
      <a href="${i}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${g}</p>
        <p><b>Downloads:</b> ${b}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function E(){m.innerHTML=""}function R(){h.classList.remove("hidden")}function $(){h.classList.add("hidden")}function M(){document.querySelector(".load-more-btn").classList.remove("hidden")}function d(){document.querySelector(".load-more-btn").classList.add("hidden")}const l=document.querySelector(".form"),p=document.querySelector(".load-more-btn");let u="",c=1,f=0;l.addEventListener("submit",async o=>{if(o.preventDefault(),u=l.elements["search-text"].value.trim(),!u){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}c=1,E(),d(),await y(),l.reset()});p.addEventListener("click",async()=>{c+=1,await y(!0)});async function y(o=!1){R();try{const r=await q(u,c),{hits:n,totalHits:i}=r;if(f=i,n.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}B(n),c*15<f?M():(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),o&&O()}catch{a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{$()}}function O(){const o=document.querySelector(".gallery .photo-card");if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:2*r,behavior:"smooth"})}p.classList.add("hidden");
//# sourceMappingURL=index.js.map
